services:
  - type: web
    name: medical-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: flask run --host=0.0.0.0 --port=5000
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
